# docker-compose up -d --build
# based on https://medium.com/@lojorider/docker-with-cgi-perl-a4558ab6a329

version: '3'
services:
    web:
        container_name: recipes
        build:
            context: .
        volumes:
            - ./weblog:/var/log/nginx/web
        restart: always
        ports:
            - "8086:80"

networks:
   default:
       external:
          name: RichiNet
